"""QAD M6 — Source Intelligence / Gemini Notebook Engineering (FD #151).

Deterministic M6 core, implemented cluster by cluster behind the frozen QAD
abstractions. M6.1 (archive admission attestation) lives here in ``eligibility``;
later clusters (SEALED snapshot builder, run ledger, provider adapter) follow in
dependency order per FD #151.
"""

from __future__ import annotations

from qad.m6.eligibility import (
    SealedEligibility,
    SRCV_ONLY_CAPTURE_PROOF_INELIGIBLE,
    evaluate_sealed_source_eligibility,
)
from qad.m6.ledger import (
    CANONICAL_SCHEMA_COUNT,
    RUNTIME_DATA_DIR_ENV,
    AttemptRecord,
    CandidateDisposition,
    CandidateRecord,
    DeepResearchRunLedgerStore,
    DispositionRecord,
    LedgerError,
    LedgerIdentityConflict,
    LedgerNotFound,
    LedgerStateError,
    LedgerTerminalError,
    LedgerValidationError,
    RetryMode,
    RunRecord,
    TelemetryMetric,
    TelemetryStatus,
    TerminalStatus,
    assert_outside_repository,
    default_runtime_ledger_path,
    validate_rrm_deep_research_runs,
)
from qad.m6.research_contract import (
    REQUEST_ISOLATION_UNVERIFIED,
    S10_CAPABILITY,
    ClosedCorpusEnforcement,
    DeepResearchRequest,
    DeepResearchResult,
    IsolationVerification,
    ProviderConfiguration,
    RequestAuthorityViolation,
    ResearchContractError,
    ResearchRequestError,
    ResearchResultError,
    ResearchResultStatus,
    SourceCorpusDescriptor,
    SourcePointer,
    build_deep_research_request,
    build_deep_research_result,
    compute_result_sha256,
    result_matches_hash,
    validate_ledger_linkage,
)
from qad.m6.snapshot import (
    PROVIDER_CANNOT_ENFORCE_SEALED_INPUT,
    SEALED_PIT_MODE,
    SealedInputSnapshot,
    SealedSourceSnapshot,
    SnapshotBuildError,
    SnapshotFailureCode,
    build_sealed_input_snapshot,
    input_snapshot_identity_payload,
)

__all__ = [
    "SealedEligibility",
    "SRCV_ONLY_CAPTURE_PROOF_INELIGIBLE",
    "evaluate_sealed_source_eligibility",
    "PROVIDER_CANNOT_ENFORCE_SEALED_INPUT",
    "SEALED_PIT_MODE",
    "SealedInputSnapshot",
    "SealedSourceSnapshot",
    "SnapshotBuildError",
    "SnapshotFailureCode",
    "build_sealed_input_snapshot",
    "input_snapshot_identity_payload",
    "CANONICAL_SCHEMA_COUNT",
    "RUNTIME_DATA_DIR_ENV",
    "AttemptRecord",
    "CandidateDisposition",
    "CandidateRecord",
    "DeepResearchRunLedgerStore",
    "DispositionRecord",
    "LedgerError",
    "LedgerIdentityConflict",
    "LedgerNotFound",
    "LedgerStateError",
    "LedgerTerminalError",
    "LedgerValidationError",
    "RetryMode",
    "RunRecord",
    "TelemetryMetric",
    "TelemetryStatus",
    "TerminalStatus",
    "assert_outside_repository",
    "default_runtime_ledger_path",
    "validate_rrm_deep_research_runs",
    "REQUEST_ISOLATION_UNVERIFIED",
    "S10_CAPABILITY",
    "ClosedCorpusEnforcement",
    "DeepResearchRequest",
    "DeepResearchResult",
    "IsolationVerification",
    "ProviderConfiguration",
    "RequestAuthorityViolation",
    "ResearchContractError",
    "ResearchRequestError",
    "ResearchResultError",
    "ResearchResultStatus",
    "SourceCorpusDescriptor",
    "SourcePointer",
    "build_deep_research_request",
    "build_deep_research_result",
    "compute_result_sha256",
    "result_matches_hash",
    "validate_ledger_linkage",
]
