"""
Fundamental & Opportunity V0 — Synthetic Fixtures
Per FUNDAMENTAL-OPPORTUNITY-INTELLIGENCE.md v0.1 (FD #40)
SYNTHETIC — FOR V0 TESTING ONLY. NOT LIVE DATA.
"""

FIXTURES = [
    {
        "id": "AAPL",
        "name": "Apple Inc.",
        "sector": "Technology",
        "industry": "Consumer Electronics",
        "market_cap": 3200,  # billions
        # ── Moat (§3.4.1) ──
        "moat_types": [
            {"type": "Share of Mind", "strength": "Strong",
             "evidence": "#1 consumer tech brand globally, NPS 72, brand value $500B+"},
            {"type": "High Switching Cost", "strength": "Moderate",
             "evidence": "iOS ecosystem lock-in: iMessage, iCloud, App Store, 2B+ active devices"},
            {"type": "Intangible Assets", "strength": "Weak",
             "evidence": "Design patents; many expiring. Services IP growing (Apple Pay, Fitness+)"},
        ],
        "moat_width": "Wide",
        "moat_depth": "Deep",
        "moat_trend": "Stable",
        # ── Financial Quality (§3.4) ──
        "gross_margin": 0.46,
        "operating_margin": 0.31,
        "fcf_conversion": 1.15,  # FCF/EPS
        "debt_to_equity": 1.8,
        "roe": 1.45,
        "revenue_growth_3y": 0.08,
        # ── Earnings Quality (§3.5.1) ──
        "latest_eps": 1.52,
        "consensus_eps": 1.46,
        "surprise_direction": "Beat",
        "surprise_magnitude_pct": 4.2,
        "revenue_quality": "HIGH",
        "margin_quality": "HIGH",
        "one_time_items": False,
        "share_buyback_impact_pct": 0.3,
        "guidance_direction": "Raised",
        "guidance_reason": "Organic demand — Services accelerating",
        # ── Valuation (§3.6) ──
        "pe_ttm": 31.2,
        "pe_5y_avg": 28.5,
        "pe_10y_avg": 22.0,
        "ev_ebitda": 23.4,
        "ev_ebitda_industry": 18.2,
        "fcf_yield": 0.036,
        "scenario_bull": 220,
        "scenario_base": 185,
        "scenario_bear": 140,
        "current_price": 190,
        # ── Management ──
        "ceo_tenure_years": 13,
        "management_credibility": "HIGH",
        "insider_activity": "CEO sold $50M for tax purposes — no concern",
        "cfo_turnover_3y": 0,
    },
    {
        "id": "INTC",
        "name": "Intel Corporation",
        "sector": "Technology",
        "industry": "Semiconductors",
        "market_cap": 180,
        # ── Moat ──
        "moat_types": [
            {"type": "Share of Mind", "strength": "Weak",
             "evidence": "Brand declining — 'Intel Inside' less relevant in mobile/AI era"},
            {"type": "Intangible Assets", "strength": "Weak",
             "evidence": "x86 architecture still relevant but ARM encroaching in client and server"},
        ],
        "moat_width": "Narrow",
        "moat_depth": "Shallow",
        "moat_trend": "Narrowing",
        # ── Financial Quality ──
        "gross_margin": 0.41,
        "operating_margin": 0.05,  # crumbling
        "fcf_conversion": -0.30,  # negative FCF
        "debt_to_equity": 0.55,
        "roe": 0.02,
        "revenue_growth_3y": -0.08,
        # ── Earnings Quality ──
        "latest_eps": 0.13,
        "consensus_eps": 0.20,
        "surprise_direction": "Miss",
        "surprise_magnitude_pct": -35.0,
        "revenue_quality": "LOW",
        "margin_quality": "LOW",
        "one_time_items": True,  # restructuring charges
        "share_buyback_impact_pct": 0.0,
        "guidance_direction": "Lowered",
        "guidance_reason": "PC TAM softening, foundry investment weighing on margins",
        # ── Valuation ──
        "pe_ttm": 14.0,
        "pe_5y_avg": 22.0,
        "pe_10y_avg": 18.5,
        "ev_ebitda": 7.2,
        "ev_ebitda_industry": 12.5,
        "fcf_yield": -0.02,
        "scenario_bull": 35,
        "scenario_base": 22,
        "scenario_bear": 12,
        "current_price": 22,
        # ── Management ──
        "ceo_tenure_years": 3,
        "management_credibility": "LOW",
        "insider_activity": "4th CEO in 6 years; missed foundry targets consistently",
        "cfo_turnover_3y": 2,
    },
    {
        "id": "COST",
        "name": "Costco Wholesale Corporation",
        "sector": "Consumer Staples",
        "industry": "Retail — Wholesale",
        "market_cap": 350,
        # ── Moat ──
        "moat_types": [
            {"type": "Cost Advantage", "strength": "Strong",
             "evidence": "Membership model + bulk purchasing = lowest cost structure in retail. Operating margin 3% but membership fees = pure profit."},
            {"type": "Efficient Scale", "strength": "Moderate",
             "evidence": "Limited warehouse locations per metro area — natural geographic oligopoly"},
        ],
        "moat_width": "Wide",
        "moat_depth": "Deep",
        "moat_trend": "Widening",
        # ── Financial Quality ──
        "gross_margin": 0.13,
        "operating_margin": 0.036,
        "fcf_conversion": 1.30,
        "debt_to_equity": 0.30,
        "roe": 0.28,
        "revenue_growth_3y": 0.09,
        # ── Earnings Quality ──
        "latest_eps": 3.78,
        "consensus_eps": 3.62,
        "surprise_direction": "Beat",
        "surprise_magnitude_pct": 4.4,
        "revenue_quality": "HIGH",
        "margin_quality": "MEDIUM",  # low margin business model by design
        "one_time_items": False,
        "share_buyback_impact_pct": 0.0,
        "guidance_direction": "Maintained",
        "guidance_reason": "Membership renewal rate 92.4% — steady organic growth",
        # ── Valuation ──
        "pe_ttm": 42.0,
        "pe_5y_avg": 36.5,
        "pe_10y_avg": 30.0,
        "ev_ebitda": 25.0,
        "ev_ebitda_industry": 14.5,
        "fcf_yield": 0.025,
        "scenario_bull": 650,
        "scenario_base": 520,
        "scenario_bear": 380,
        "current_price": 520,
        # ── Management ──
        "ceo_tenure_years": 12,
        "management_credibility": "HIGH",
        "insider_activity": "No material insider sales; consistent modest buying",
        "cfo_turnover_3y": 0,
    },
    {
        "id": "CRM",
        "name": "Salesforce, Inc.",
        "sector": "Technology",
        "industry": "Enterprise Software",
        "market_cap": 280,
        # ── Moat ──
        "moat_types": [
            {"type": "High Switching Cost", "strength": "Strong",
             "evidence": "CRM data integrated into sales/marketing workflows — migration pain, retraining cost, data loss risk"},
            {"type": "Network Effect", "strength": "Moderate",
             "evidence": "AppExchange ecosystem + customer community; more users = more integrations"},
        ],
        "moat_width": "Wide",
        "moat_depth": "Moderate",
        "moat_trend": "Stable",
        # ── Financial Quality ──
        "gross_margin": 0.76,
        "operating_margin": 0.20,
        "fcf_conversion": 0.95,
        "debt_to_equity": 0.25,
        "roe": 0.12,
        "revenue_growth_3y": 0.11,
        # ── Earnings Quality ──
        "latest_eps": 2.12,
        "consensus_eps": 2.08,
        "surprise_direction": "Beat",
        "surprise_magnitude_pct": 1.9,
        "revenue_quality": "MEDIUM",  # growth slowing from 20% to 11%
        "margin_quality": "HIGH",  # margin expanding via efficiency
        "one_time_items": False,
        "share_buyback_impact_pct": 1.2,
        "guidance_direction": "Maintained",
        "guidance_reason": "Revenue growth decelerating but margins improving",
        # ── Valuation ──
        "pe_ttm": 25.0,
        "pe_5y_avg": 55.0,
        "pe_10y_avg": 65.0,
        "ev_ebitda": 18.0,
        "ev_ebitda_industry": 22.0,
        "fcf_yield": 0.04,
        "scenario_bull": 320,
        "scenario_base": 255,
        "scenario_bear": 180,
        "current_price": 255,
        # ── Management ──
        "ceo_tenure_years": 24,  # Marc Benioff, founder
        "management_credibility": "HIGH",
        "insider_activity": "CEO sold shares per 10b5-1 plan — routine diversification",
        "cfo_turnover_3y": 1,
    },
    {
        "id": "XYZ",
        "name": "XYZ Legacy Manufacturing (Synthetic — Cosmetic Beat)",
        "sector": "Industrials",
        "industry": "Industrial Machinery",
        "market_cap": 45,
        # ── Moat ──
        "moat_types": [],
        "moat_width": "None",
        "moat_depth": "Shallow",
        "moat_trend": "Narrowing",
        # ── Financial Quality ──
        "gross_margin": 0.28,
        "operating_margin": 0.09,
        "fcf_conversion": 0.40,  # low quality
        "debt_to_equity": 1.5,
        "roe": 0.08,
        "revenue_growth_3y": -0.03,
        # ── Earnings Quality (COSMETIC — the point of this fixture) ──
        "latest_eps": 1.20,
        "consensus_eps": 1.00,
        "surprise_direction": "Beat",
        "surprise_magnitude_pct": 20.0,
        "revenue_quality": "LOW",  # revenue declining!
        "margin_quality": "LOW",
        "one_time_items": True,  # $0.15 EPS from legal settlement
        "share_buyback_impact_pct": 4.0,  # bought back 4% of shares — masking EPS decline
        "guidance_direction": "Unchanged",
        "guidance_reason": "Management avoided guidance update despite revenue decline",
        # ── Valuation ──
        "pe_ttm": 8.5,
        "pe_5y_avg": 15.0,
        "pe_10y_avg": 14.0,
        "ev_ebitda": 5.5,
        "ev_ebitda_industry": 11.0,
        "fcf_yield": 0.045,  # low quality FCF
        "scenario_bull": 55,
        "scenario_base": 32,
        "scenario_bear": 18,
        "current_price": 32,
        # ── Management ──
        "ceo_tenure_years": 2,
        "management_credibility": "LOW",
        "insider_activity": "CFO resigned last quarter; CEO sold 30% of holdings",
        "cfo_turnover_3y": 2,
    },
    {
        "id": "MSFT",
        "name": "Microsoft Corporation",
        "sector": "Technology",
        "industry": "Enterprise Software & Cloud",
        "market_cap": 3100,
        "moat_types": [
            {"type": "Network Effect", "strength": "Strong",
             "evidence": "Azure + Office 365 + LinkedIn + GitHub — enterprise ecosystems with network lock-in; developers trained on MS stack"},
            {"type": "High Switching Cost", "strength": "Strong",
             "evidence": "Enterprise agreements, Azure migrations complex ($100K+), Office 365 integrated into workflows, Active Directory entrenched"},
            {"type": "Intangible Assets", "strength": "Strong",
             "evidence": "Windows OS IP, Office IP, GitHub, OpenAI partnership/exclusivity, $25B+ annual R&D"},
        ],
        "moat_width": "Wide",
        "moat_depth": "Deep",
        "moat_trend": "Widening",
        "gross_margin": 0.70,
        "operating_margin": 0.44,
        "fcf_conversion": 1.20,
        "debt_to_equity": 0.20,
        "roe": 0.38,
        "revenue_growth_3y": 0.15,
        "latest_eps": 2.94,
        "consensus_eps": 2.82,
        "surprise_direction": "Beat",
        "surprise_magnitude_pct": 4.3,
        "revenue_quality": "HIGH",
        "margin_quality": "HIGH",
        "one_time_items": False,
        "share_buyback_impact_pct": 0.5,
        "guidance_direction": "Raised",
        "guidance_reason": "Azure accelerating +30% YoY; AI Copilot monetization beginning",
        "pe_ttm": 37.0,
        "pe_5y_avg": 33.0,
        "pe_10y_avg": 28.0,
        "ev_ebitda": 28.0,
        "ev_ebitda_industry": 22.0,
        "fcf_yield": 0.032,
        "scenario_bull": 480,
        "scenario_base": 415,
        "scenario_bear": 320,
        "current_price": 415,
        "ceo_tenure_years": 10,
        "management_credibility": "HIGH",
        "insider_activity": "CEO sold shares per 10b5-1 plan — routine diversification",
        "cfo_turnover_3y": 0,
    },
    {
        "id": "JNJ",
        "name": "Johnson & Johnson",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals & Medical Devices",
        "market_cap": 390,
        "moat_types": [
            {"type": "Intangible Assets", "strength": "Strong",
             "evidence": "Patent portfolio across oncology, immunology, neuroscience. FDA approvals as regulatory barrier. Stelara, Darzalex, Tremfya blockbusters."},
            {"type": "Efficient Scale", "strength": "Moderate",
             "evidence": "Pharma R&D scale — $15B annual R&D spend creates barrier smaller players cannot match. Manufacturing complexity for biologics."},
        ],
        "moat_width": "Wide",
        "moat_depth": "Deep",
        "moat_trend": "Stable",
        "gross_margin": 0.68,
        "operating_margin": 0.28,
        "fcf_conversion": 1.10,
        "debt_to_equity": 0.40,
        "roe": 0.30,
        "revenue_growth_3y": 0.06,
        "latest_eps": 2.29,
        "consensus_eps": 2.27,
        "surprise_direction": "Beat",
        "surprise_magnitude_pct": 0.9,
        "revenue_quality": "HIGH",
        "margin_quality": "HIGH",
        "one_time_items": False,
        "share_buyback_impact_pct": 0.8,
        "guidance_direction": "Maintained",
        "guidance_reason": "Steady pharma pipeline execution; MedTech recovering post-COVID",
        "pe_ttm": 16.0,
        "pe_5y_avg": 17.5,
        "pe_10y_avg": 16.5,
        "ev_ebitda": 13.5,
        "ev_ebitda_industry": 14.0,
        "fcf_yield": 0.055,
        "scenario_bull": 185,
        "scenario_base": 160,
        "scenario_bear": 130,
        "current_price": 160,
        "ceo_tenure_years": 2,
        "management_credibility": "HIGH",
        "insider_activity": "New CEO from internal promotion — continuity signal",
        "cfo_turnover_3y": 0,
    },
    {
        "id": "GE",
        "name": "General Electric",
        "sector": "Industrials",
        "industry": "Aerospace & Power",
        "market_cap": 175,
        "moat_types": [
            {"type": "Efficient Scale", "strength": "Moderate",
             "evidence": "Aerospace engine duopoly with Rolls-Royce/Pratt & Whitney. Long service contracts create recurring revenue streams. GE Aerospace is the surviving crown jewel post-breakup."},
        ],
        "moat_width": "Narrow",
        "moat_depth": "Moderate",
        "moat_trend": "Narrowing",
        "gross_margin": 0.26,
        "operating_margin": 0.12,
        "fcf_conversion": 0.70,
        "debt_to_equity": 0.65,
        "roe": 0.10,
        "revenue_growth_3y": 0.04,
        "latest_eps": 0.68,
        "consensus_eps": 0.72,
        "surprise_direction": "Miss",
        "surprise_magnitude_pct": -5.6,
        "revenue_quality": "MEDIUM",
        "margin_quality": "MEDIUM",
        "one_time_items": True,
        "share_buyback_impact_pct": 0.0,
        "guidance_direction": "Maintained",
        "guidance_reason": "Post-breakup stabilization; legacy liabilities winding down",
        "pe_ttm": 12.0,
        "pe_5y_avg": 25.0,
        "pe_10y_avg": 20.0,
        "ev_ebitda": 9.5,
        "ev_ebitda_industry": 12.0,
        "fcf_yield": 0.035,
        "scenario_bull": 140,
        "scenario_base": 105,
        "scenario_bear": 70,
        "current_price": 105,
        "ceo_tenure_years": 5,
        "management_credibility": "MEDIUM",
        "insider_activity": "CEO bought $2M in shares post-breakup — modest confidence signal",
        "cfo_turnover_3y": 1,
    },
]

# Macro regime context (applied to all companies)
MACRO_REGIME = {
    "regime": "Growth — Late Cycle",
    "gdp_growth": 0.025,
    "inflation": 0.031,
    "fed_funds": 0.0525,
    "yield_curve": "Flat",
    "credit_spreads": "Narrow",
    "sector_implications": {
        "Technology": "Neutral — AI capex tailwind, valuation headwind from rates",
        "Consumer Staples": "Slight headwind — consumer slowing, but staples defensive",
        "Industrials": "Neutral — manufacturing PMI 48.7 (contracting), but infra spending supportive",
        "Healthcare": "Neutral — defensive sector, patent cliff risk offset by aging demographics",
    },
}
