"""Canonical Boundary (auto-generated from M4A parser)."""

# Canonical schemas
CANONICAL_SCHEMAS = {
    "AF-01",
    "AG-01",
    "BU-01",
    "CAE-01",
    "CALC-01",
    "CASE-01",
    "CCV-01",
    "CE-01",
    "CL-01",
    "CLK-01",
    "CLM-01",
    "CR-01",
    "CRESP-01",
    "CTR-01",
    "DR-01",
    "EAR-01",
    "EG-01",
    "EHR-01",
    "EV-01",
    "FACT-01",
    "FDR-01",
    "FE-01",
    "FF-01",
    "HS-01",
    "HYP-01",
    "IA-01",
    "IC-01",
    "IE-01",
    "IKR-01",
    "INF-01",
    "IPR-01",
    "IR-01",
    "MA-01",
    "MASS-01",
    "MC-01",
    "MDL-01",
    "MI-01",
    "MO-01",
    "MO-02",
    "MOD-01",
    "NFF-01",
    "PIE-01",
    "PITC-01",
    "PLA-01",
    "PROV-01",
    "PUB-01",
    "QA-01",
    "QU-01",
    "RB-01",
    "RC-01",
    "RDCF-01",
    "RFR-01",
    "RM-01",
    "RR-01",
    "RRM-01",
    "RSR-01",
    "RSR-02",
    "RTC-01",
    "RU-01",
    "SCEN-01",
    "SI-01",
    "SM-01",
    "SR-01",
    "SRC-01",
    "SRCV-01",
    "TK-01",
    "UV-01",
    "VA-01",
}

# Non-canonical schemas
NON_CANONICAL_SCHEMAS = {
}

# Family index (infrastructure = Family I)
SCHEMA_FAMILIES = {
    "AF-01": "G",
    "AG-01": "G",
    "BU-01": "I",
    "CAE-01": "D",
    "CALC-01": "F",
    "CASE-01": "A",
    "CCV-01": "H",
    "CE-01": "E",
    "CL-01": "H",
    "CLK-01": "I",
    "CLM-01": "B",
    "CR-01": "A",
    "CRESP-01": "G",
    "CTR-01": "B",
    "DR-01": "E",
    "EAR-01": "B",
    "EG-01": "B",
    "EHR-01": "I",
    "EV-01": "B",
    "FACT-01": "B",
    "FDR-01": "G",
    "FE-01": "E",
    "FF-01": "F",
    "HS-01": "C",
    "HYP-01": "B",
    "IA-01": "E",
    "IC-01": "C",
    "IE-01": "D",
    "IKR-01": "H",
    "INF-01": "B",
    "IPR-01": "H",
    "IR-01": "C",
    "MA-01": "D",
    "MASS-01": "H",
    "MC-01": "D",
    "MDL-01": "D",
    "MI-01": "H",
    "MO-01": "H",
    "MO-02": "D",
    "MOD-01": "I",
    "NFF-01": "F",
    "PIE-01": "F",
    "PITC-01": "I",
    "PLA-01": "F",
    "PROV-01": "I",
    "PUB-01": "G",
    "QA-01": "D",
    "QU-01": "A",
    "RB-01": "C",
    "RC-01": "C",
    "RDCF-01": "F",
    "RFR-01": "C",
    "RM-01": "E",
    "RR-01": "I",
    "RRM-01": "I",
    "RSR-01": "C",
    "RSR-02": "C",
    "RTC-01": "G",
    "RU-01": "A",
    "SCEN-01": "F",
    "SI-01": "I",
    "SM-01": "A",
    "SR-01": "A",
    "SRC-01": "B",
    "SRCV-01": "B",
    "TK-01": "E",
    "UV-01": "G",
    "VA-01": "F",
}

# Canonical boundary text (preserved exactly from M4A)
CANONICAL_BOUNDARY_TEXT = {
    "AF-01": "Canonical.",
    "AG-01": "Canonical.",
    "BU-01": "Canonical.",
    "CAE-01": "Canonical.",
    "CALC-01": "Canonical.",
    "CASE-01": "Canonical.",
    "CCV-01": "Canonical.",
    "CE-01": "Canonical.",
    "CL-01": "Canonical.",
    "CLK-01": "Canonical.",
    "CLM-01": "Canonical.",
    "CR-01": "Canonical.",
    "CRESP-01": "Canonical.",
    "CTR-01": "Canonical.",
    "DR-01": "Canonical.",
    "EAR-01": "Canonical (audit layer).",
    "EG-01": "Canonical.",
    "EHR-01": "Canonical.",
    "EV-01": "Canonical (Layer 2). NotebookLM/DR output is NONCANONICAL until validated.",
    "FACT-01": "Canonical.",
    "FDR-01": "Canonical (final authority).",
    "FE-01": "Canonical.",
    "FF-01": "Canonical.",
    "HS-01": "Canonical.",
    "HYP-01": "Canonical.",
    "IA-01": "Canonical.",
    "IC-01": "Canonical.",
    "IE-01": "Canonical.",
    "IKR-01": "Canonical.",
    "INF-01": "Canonical.",
    "IPR-01": "Canonical.",
    "IR-01": "Canonical. Proposed evidence noncanonical until admitted.",
    "MA-01": "Canonical.",
    "MASS-01": "Canonical.",
    "MC-01": "Canonical.",
    "MDL-01": "Canonical.",
    "MI-01": "Canonical.",
    "MO-01": "Canonical.",
    "MO-02": "Canonical.",
    "MOD-01": "Canonical.",
    "NFF-01": "Canonical.",
    "PIE-01": "Canonical.",
    "PITC-01": "Canonical.",
    "PLA-01": "Canonical.",
    "PROV-01": "Canonical.",
    "PUB-01": "Publication is NONCANONICAL for investment truth. Canonical for record.",
    "QA-01": "Canonical.",
    "QU-01": "Canonical.",
    "RB-01": "Canonical.",
    "RC-01": "Canonical.",
    "RDCF-01": "Canonical.",
    "RFR-01": "Canonical.",
    "RM-01": "Canonical.",
    "RR-01": "Canonical.",
    "RRM-01": "Canonical.",
    "RSR-01": "Canonical.",
    "RSR-02": "Canonical.",
    "RTC-01": "Canonical.",
    "RU-01": "Canonical.",
    "SCEN-01": "Canonical.",
    "SI-01": "Canonical.",
    "SM-01": "Canonical. All other registries reference SM-01 entity_id.",
    "SR-01": "Canonical.",
    "SRC-01": "Canonical (Layer 1: Raw Source Archive).",
    "SRCV-01": "Canonical.",
    "TK-01": "Canonical.",
    "UV-01": "Canonical. Recommendation to Founder is advisory.",
    "VA-01": "Canonical.",
}