"""QAD Runtime Schema Models — all 68 frozen M4A canonical schemas."""
from __future__ import annotations

from qad.models.family_a import (
    CaseRecord,
    CandidateRecord,
    QualityUniverseRecord,
    ResearchableUniverseRecord,
    SecurityMaster,
    SignalRecord,
)

from qad.models.family_b import (
    ClaimRecord,
    ContradictionRecord,
    EvidenceAdmissionRecord,
    EvidenceGap,
    EvidenceRecord,
    FactRecord,
    HypothesisRecord,
    InferenceRecord,
    SourceRecord,
    SourceVersion,
)

from qad.models.family_c import (
    HypothesisSet,
    InvestigatorCharter,
    InvestigationReport,
    ResearchBudgetRecord,
    ResearchCharter,
    ResearchFailureRecord,
    ResearchStageRecord,
    ResearchStopRecord,
)

from qad.models.family_d import (
    CapitalAllocationEvent,
    IndustryEconomicsRecord,
    MoatAssessment,
    ManagementClaim,
    ManagementDecisionLedger,
    ManagementOutcome,
    QualityAssessment,
)

from qad.models.family_e import (
    CompetingExplanation,
    DislocationRecord,
    FlipEvidence,
    ImpairmentAssessment,
    RecoveryModel,
    ThesisKiller,
)

from qad.models.family_f import (
    CalculationRecord,
    FinancialFact,
    NormalizedFinancialFact,
    PriceImpliedExpectation,
    PermanentLossAssessment,
    ReverseDCFRecord,
    ScenarioRecord,
    ValuationAssessment,
)

from qad.models.family_g import (
    AuditFinding,
    AuditGate,
    ChallengeResponse,
    FounderDecisionReference,
    PublicationRecord,
    RedTeamChallenge,
    UnderwritingVerdict,
)

from qad.models.family_h import (
    CrossCaseValidation,
    CandidateLesson,
    InstitutionalKnowledgeRecord,
    IndustryPlaybookRecord,
    MonitoringAssessment,
    MonitoringIndicator,
    MonitoringObservation,
)

from qad.models.family_i import (
    BudgetUsage,
    CaseLock,
    EvaluationHarnessRun,
    ModelInvocation,
    PITContext,
    ProviderInvocation,
    RetryRecord,
    RunManifestRecord,
    ServiceInvocation,
)


__all__ = [
    "AuditFinding",
    "AuditGate",
    "BudgetUsage",
    "CalculationRecord",
    "CandidateLesson",
    "CandidateRecord",
    "CapitalAllocationEvent",
    "CaseLock",
    "CaseRecord",
    "ChallengeResponse",
    "ClaimRecord",
    "CompetingExplanation",
    "ContradictionRecord",
    "CrossCaseValidation",
    "DislocationRecord",
    "EvaluationHarnessRun",
    "EvidenceAdmissionRecord",
    "EvidenceGap",
    "EvidenceRecord",
    "FactRecord",
    "FinancialFact",
    "FlipEvidence",
    "FounderDecisionReference",
    "HypothesisRecord",
    "HypothesisSet",
    "ImpairmentAssessment",
    "IndustryEconomicsRecord",
    "IndustryPlaybookRecord",
    "InferenceRecord",
    "InstitutionalKnowledgeRecord",
    "InvestigationReport",
    "InvestigatorCharter",
    "ManagementClaim",
    "ManagementDecisionLedger",
    "ManagementOutcome",
    "MoatAssessment",
    "ModelInvocation",
    "MonitoringAssessment",
    "MonitoringIndicator",
    "MonitoringObservation",
    "NormalizedFinancialFact",
    "PITContext",
    "PermanentLossAssessment",
    "PriceImpliedExpectation",
    "ProviderInvocation",
    "PublicationRecord",
    "QualityAssessment",
    "QualityUniverseRecord",
    "RecoveryModel",
    "RedTeamChallenge",
    "ResearchBudgetRecord",
    "ResearchCharter",
    "ResearchFailureRecord",
    "ResearchStageRecord",
    "ResearchStopRecord",
    "ResearchableUniverseRecord",
    "RetryRecord",
    "ReverseDCFRecord",
    "RunManifestRecord",
    "ScenarioRecord",
    "SecurityMaster",
    "ServiceInvocation",
    "SignalRecord",
    "SourceRecord",
    "SourceVersion",
    "ThesisKiller",
    "UnderwritingVerdict",
    "ValuationAssessment",
]


# Schema registry: maps schema_id to model class (auto-generated)
SCHEMA_REGISTRY: dict[str, type] = {
    "AF-01": AuditFinding,
    "AG-01": AuditGate,
    "BU-01": BudgetUsage,
    "CAE-01": CapitalAllocationEvent,
    "CALC-01": CalculationRecord,
    "CASE-01": CaseRecord,
    "CCV-01": CrossCaseValidation,
    "CE-01": CompetingExplanation,
    "CL-01": CandidateLesson,
    "CLK-01": CaseLock,
    "CLM-01": ClaimRecord,
    "CR-01": CandidateRecord,
    "CRESP-01": ChallengeResponse,
    "CTR-01": ContradictionRecord,
    "DR-01": DislocationRecord,
    "EAR-01": EvidenceAdmissionRecord,
    "EG-01": EvidenceGap,
    "EHR-01": EvaluationHarnessRun,
    "EV-01": EvidenceRecord,
    "FACT-01": FactRecord,
    "FDR-01": FounderDecisionReference,
    "FE-01": FlipEvidence,
    "FF-01": FinancialFact,
    "HS-01": HypothesisSet,
    "HYP-01": HypothesisRecord,
    "IA-01": ImpairmentAssessment,
    "IC-01": InvestigatorCharter,
    "IE-01": IndustryEconomicsRecord,
    "IKR-01": InstitutionalKnowledgeRecord,
    "INF-01": InferenceRecord,
    "IPR-01": IndustryPlaybookRecord,
    "IR-01": InvestigationReport,
    "MA-01": MoatAssessment,
    "MASS-01": MonitoringAssessment,
    "MC-01": ManagementClaim,
    "MDL-01": ManagementDecisionLedger,
    "MI-01": MonitoringIndicator,
    "MO-01": MonitoringObservation,
    "MO-02": ManagementOutcome,
    "MOD-01": ModelInvocation,
    "NFF-01": NormalizedFinancialFact,
    "PIE-01": PriceImpliedExpectation,
    "PITC-01": PITContext,
    "PLA-01": PermanentLossAssessment,
    "PROV-01": ProviderInvocation,
    "PUB-01": PublicationRecord,
    "QA-01": QualityAssessment,
    "QU-01": QualityUniverseRecord,
    "RB-01": ResearchBudgetRecord,
    "RC-01": ResearchCharter,
    "RDCF-01": ReverseDCFRecord,
    "RFR-01": ResearchFailureRecord,
    "RM-01": RecoveryModel,
    "RR-01": RetryRecord,
    "RRM-01": RunManifestRecord,
    "RSR-01": ResearchStageRecord,
    "RSR-02": ResearchStopRecord,
    "RTC-01": RedTeamChallenge,
    "RU-01": ResearchableUniverseRecord,
    "SCEN-01": ScenarioRecord,
    "SI-01": ServiceInvocation,
    "SM-01": SecurityMaster,
    "SR-01": SignalRecord,
    "SRC-01": SourceRecord,
    "SRCV-01": SourceVersion,
    "TK-01": ThesisKiller,
    "UV-01": UnderwritingVerdict,
    "VA-01": ValuationAssessment,
}


# Machine-readable build identity (auto-generated)
SCHEMA_BUILD_IDENTITY: dict[str, object] = {
    "spec_source": "QAD-M4A-CANONICAL-SCHEMAS.md",
    "spec_source_sha256": "6755cff07cbb240a8bab8eb49ab39894f5673c73322e51c4e2ead932f706dfa6",
    "m4a_contract_version": "M4A-FROZEN+ERRATUM-001",
    "generator_version": "M5.1-20260824",
    "total_schemas": 68,
    "total_models": 68,
    "generated_artifact_hashes": {
    "models/family_a.py": "1a83970964f6d4e232d4b6a793f5cee20ccc57887ae2cfd0b919cfb97ab368fd",
    "models/family_b.py": "d5104184c90d0b56e505460306d5c37a7840ac8c19c9b4ec1c3c6e432f6c43ea",
    "models/family_c.py": "8d5e5e6d959797f87c5e8a718fc11a78a120fc07ccbbc31d3aed30cd8ca36380",
    "models/family_d.py": "8a6c4f4c9aebc12d019ac7b505ae16b7baa5e015f07a30b315e39c3573bb24b4",
    "models/family_e.py": "a111bde88ae0a1bf344f6b7da9d53b166a972865c0cd64074b15f17f896552e0",
    "models/family_f.py": "e6d281bf35f8165b0dfe05790a3c114f6ec41b0ed7c7ea2c85c2e3a22e2a448e",
    "models/family_g.py": "1eebac3e06f439cf29512fe25169ba64fdbb5191397bad964e39a6960638f4e1",
    "models/family_h.py": "51ca3b8ba338322a624e6536cb986b94684ecdc96a06bffa412bd79708e8c9a7",
    "models/family_i.py": "167efb03dc5772494cd3b7a7663388808d1ed499394d49eb52b4b284e58afcbc",
    "contract/fk_registry.py": "d811495b85382ed4495045c151d4d760b22d01874cbb56247a47dda20e562e4b",
    "contract/canonical_boundary.py": "87ee2db47d70f0c25fdcb6733608624e392d18326f56439736ce044ec13b6c91",
    "contract/contract_descriptor.json": "74ab6622dc05f30aeea521351477532d23bb5f3c7322bc2fc1c79df2ed8a7629"
},
}