"""QAD Runtime Schema Models — all 68 frozen M4A canonical schemas."""
from __future__ import annotations

from qad.models.family_a import (
    CaseRecord,
    CandidateRecord,
    QualityUniverseRecord,
    ResearchableUniverseRecord,
    SecurityMaster,
    SignalRecord,
)

from qad.models.family_b import (
    ClaimRecord,
    ContradictionRecord,
    EvidenceAdmissionRecord,
    EvidenceGap,
    EvidenceRecord,
    FactRecord,
    HypothesisRecord,
    InferenceRecord,
    SourceRecord,
    SourceVersion,
)

from qad.models.family_c import (
    HypothesisSet,
    InvestigatorCharter,
    InvestigationReport,
    ResearchBudgetRecord,
    ResearchCharter,
    ResearchFailureRecord,
    ResearchStageRecord,
    ResearchStopRecord,
)

from qad.models.family_d import (
    CapitalAllocationEvent,
    IndustryEconomicsRecord,
    MoatAssessment,
    ManagementClaim,
    ManagementDecisionLedger,
    ManagementOutcome,
    QualityAssessment,
)

from qad.models.family_e import (
    CompetingExplanation,
    DislocationRecord,
    FlipEvidence,
    ImpairmentAssessment,
    RecoveryModel,
    ThesisKiller,
)

from qad.models.family_f import (
    CalculationRecord,
    FinancialFact,
    NormalizedFinancialFact,
    PriceImpliedExpectation,
    PermanentLossAssessment,
    ReverseDCFRecord,
    ScenarioRecord,
    ValuationAssessment,
)

from qad.models.family_g import (
    AuditFinding,
    AuditGate,
    ChallengeResponse,
    FounderDecisionReference,
    PublicationRecord,
    RedTeamChallenge,
    UnderwritingVerdict,
)

from qad.models.family_h import (
    CrossCaseValidation,
    CandidateLesson,
    InstitutionalKnowledgeRecord,
    IndustryPlaybookRecord,
    MonitoringAssessment,
    MonitoringIndicator,
    MonitoringObservation,
)

from qad.models.family_i import (
    BudgetUsage,
    CaseLock,
    EvaluationHarnessRun,
    ModelInvocation,
    PITContext,
    ProviderInvocation,
    RetryRecord,
    RunManifestRecord,
    ServiceInvocation,
)


__all__ = [
    "AuditFinding",
    "AuditGate",
    "BudgetUsage",
    "CalculationRecord",
    "CandidateLesson",
    "CandidateRecord",
    "CapitalAllocationEvent",
    "CaseLock",
    "CaseRecord",
    "ChallengeResponse",
    "ClaimRecord",
    "CompetingExplanation",
    "ContradictionRecord",
    "CrossCaseValidation",
    "DislocationRecord",
    "EvaluationHarnessRun",
    "EvidenceAdmissionRecord",
    "EvidenceGap",
    "EvidenceRecord",
    "FactRecord",
    "FinancialFact",
    "FlipEvidence",
    "FounderDecisionReference",
    "HypothesisRecord",
    "HypothesisSet",
    "ImpairmentAssessment",
    "IndustryEconomicsRecord",
    "IndustryPlaybookRecord",
    "InferenceRecord",
    "InstitutionalKnowledgeRecord",
    "InvestigationReport",
    "InvestigatorCharter",
    "ManagementClaim",
    "ManagementDecisionLedger",
    "ManagementOutcome",
    "MoatAssessment",
    "ModelInvocation",
    "MonitoringAssessment",
    "MonitoringIndicator",
    "MonitoringObservation",
    "NormalizedFinancialFact",
    "PITContext",
    "PermanentLossAssessment",
    "PriceImpliedExpectation",
    "ProviderInvocation",
    "PublicationRecord",
    "QualityAssessment",
    "QualityUniverseRecord",
    "RecoveryModel",
    "RedTeamChallenge",
    "ResearchBudgetRecord",
    "ResearchCharter",
    "ResearchFailureRecord",
    "ResearchStageRecord",
    "ResearchStopRecord",
    "ResearchableUniverseRecord",
    "RetryRecord",
    "ReverseDCFRecord",
    "RunManifestRecord",
    "ScenarioRecord",
    "SecurityMaster",
    "ServiceInvocation",
    "SignalRecord",
    "SourceRecord",
    "SourceVersion",
    "ThesisKiller",
    "UnderwritingVerdict",
    "ValuationAssessment",
]


# Schema registry: maps schema_id to model class (auto-generated)
SCHEMA_REGISTRY: dict[str, type] = {
    "AF-01": AuditFinding,
    "AG-01": AuditGate,
    "BU-01": BudgetUsage,
    "CAE-01": CapitalAllocationEvent,
    "CALC-01": CalculationRecord,
    "CASE-01": CaseRecord,
    "CCV-01": CrossCaseValidation,
    "CE-01": CompetingExplanation,
    "CL-01": CandidateLesson,
    "CLK-01": CaseLock,
    "CLM-01": ClaimRecord,
    "CR-01": CandidateRecord,
    "CRESP-01": ChallengeResponse,
    "CTR-01": ContradictionRecord,
    "DR-01": DislocationRecord,
    "EAR-01": EvidenceAdmissionRecord,
    "EG-01": EvidenceGap,
    "EHR-01": EvaluationHarnessRun,
    "EV-01": EvidenceRecord,
    "FACT-01": FactRecord,
    "FDR-01": FounderDecisionReference,
    "FE-01": FlipEvidence,
    "FF-01": FinancialFact,
    "HS-01": HypothesisSet,
    "HYP-01": HypothesisRecord,
    "IA-01": ImpairmentAssessment,
    "IC-01": InvestigatorCharter,
    "IE-01": IndustryEconomicsRecord,
    "IKR-01": InstitutionalKnowledgeRecord,
    "INF-01": InferenceRecord,
    "IPR-01": IndustryPlaybookRecord,
    "IR-01": InvestigationReport,
    "MA-01": MoatAssessment,
    "MASS-01": MonitoringAssessment,
    "MC-01": ManagementClaim,
    "MDL-01": ManagementDecisionLedger,
    "MI-01": MonitoringIndicator,
    "MO-01": MonitoringObservation,
    "MO-02": ManagementOutcome,
    "MOD-01": ModelInvocation,
    "NFF-01": NormalizedFinancialFact,
    "PIE-01": PriceImpliedExpectation,
    "PITC-01": PITContext,
    "PLA-01": PermanentLossAssessment,
    "PROV-01": ProviderInvocation,
    "PUB-01": PublicationRecord,
    "QA-01": QualityAssessment,
    "QU-01": QualityUniverseRecord,
    "RB-01": ResearchBudgetRecord,
    "RC-01": ResearchCharter,
    "RDCF-01": ReverseDCFRecord,
    "RFR-01": ResearchFailureRecord,
    "RM-01": RecoveryModel,
    "RR-01": RetryRecord,
    "RRM-01": RunManifestRecord,
    "RSR-01": ResearchStageRecord,
    "RSR-02": ResearchStopRecord,
    "RTC-01": RedTeamChallenge,
    "RU-01": ResearchableUniverseRecord,
    "SCEN-01": ScenarioRecord,
    "SI-01": ServiceInvocation,
    "SM-01": SecurityMaster,
    "SR-01": SignalRecord,
    "SRC-01": SourceRecord,
    "SRCV-01": SourceVersion,
    "TK-01": ThesisKiller,
    "UV-01": UnderwritingVerdict,
    "VA-01": ValuationAssessment,
}


# Machine-readable build identity (auto-generated)
SCHEMA_BUILD_IDENTITY: dict[str, object] = {
    "spec_source": "QAD-M4A-CANONICAL-SCHEMAS.md",
    "spec_source_sha256": "d4b27d82e72fa856c334709abbcc808eb14c3a7d2c4b710b29ffdb847b2a49ba",
    "m4a_contract_version": "M4A-FROZEN-20260821",
    "generator_version": "M5.1-20260824",
    "total_schemas": 68,
    "total_models": 68,
    # generated_artifact_hashes populated post-generation via regeneration test
}